# Generated by Django 5.0.1 on 2024-10-23 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_date', models.DateTimeField()),
                ('team1', models.CharField(max_length=100)),
                ('team2', models.CharField(max_length=100)),
                ('result', models.CharField(blank=True, max_length=10, null=True)),
                ('odds_ft_home_team_win', models.DecimalField(decimal_places=2, max_digits=5)),
                ('odds_ft_draw', models.DecimalField(decimal_places=2, max_digits=5)),
                ('odds_ft_away_team_win', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
