# Generated by Django 5.0.1 on 2024-10-23 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_bet_betselection_coupon_betselection_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
