# Generated by Django 5.0.1 on 2024-10-24 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_coupon_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='potential_winnings',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='stake',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='total_odds',
            field=models.DecimalField(decimal_places=4, max_digits=5),
        ),
    ]
