# Generated by Django 5.0.1 on 2024-10-24 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_coupon_potential_winnings_alter_coupon_stake_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='potential_winnings',
            field=models.DecimalField(decimal_places=4, max_digits=12),
        ),
    ]
